### ISSUE TITLE
Trouble running demo:protocol in Firefox 63.0a1

### ISSUE THREAD

**Issue by lidel** [mozilla/libdweb#16] opened 2018-07-09 14:36 UTC
@Gozala  I tried to run `npm run demo:protocol` from latest `HEAD` in  Firefox Nightly 63.0a1 and got:

![2018-07-09_16-31](https://user-images.githubusercontent.com/157609/42456641-b60288c0-8395-11e8-8fcc-7cc72953c681.png)

Is this a regression or something on my end?

**Comment by soapdog** [comment] 2018-07-12 13:36
@lidel can confirm this happening on my copy of Nightly as well.

**Comment by soapdog** [comment] 2018-07-12 14:03
@lidel I thinking it might be worse than that. I can't run any of the demos, they are all failing for me. I am on windows and I've patched the `npm run` scripts here to run on my platform as shown in #18.

I receive a ton of errors. I am trying to investigate that but I suspect some regression. @Gozala and @autonome, can you double check the demos on current nightly please?

**Comment by soapdog** [comment] 2018-07-12 14:43
Got the protocol demo to run on _Firefox Developer Edition_ but the others didn't. The _filesystem_ demo appears to be launching, at least I can mount a folder but I can't make anything else work. Maybe I am using it wrong, the instructions are not clear.

**Comment by Gozala** [comment] 2018-07-12 17:56
I just checked and I see same error, I suspect something has changed on nightly. I'll be investigating this issue and post any updates here. In the meantime Dev edition or older nightly build might be a way to go about this.

**Comment by Gozala** [comment] 2018-07-12 18:00
Looks like it's coming from https://github.com/mozilla/libdweb/blob/48558a2026480e0fc32a4843a5d4d3a7df001167/src/protocol/router.js#L55 and I guess `resource://gre/modules/XPCOMUtils.jsm` no longer has `getConsole`. Technically we don't really need console in there so should be easy enough to fix.

**Comment by Gozala** [comment] 2018-07-12 18:11
Fixed by d781ba3

**Closed by Gozala** 2018-07-12 18:11 UTC
